Fix bug in 'sendvidhop --delete'.

diff --git a/bin/fvid b/bin/fvid
--- a/bin/fvid
+++ b/bin/fvid
@@ -7,9 +7,10 @@ function fvid_help() {
   echo "    fvid <SEARCH_TEXT>  => find videos where title or description matches <SEARCH_TEXT> in all videos and channels metadata"
   echo "    fvidv <SEARCH_TEXT> => find videos where title or description matches <SEARCH_TEXT> in all videos metadata (shorter search time)"
   echo "    fvidf <SEARCH_TEXT> => find videos where title or description matches <SEARCH_TEXT> in all video files on disk"
+  echo "    fvidfc <TITLE_SEARCH_TEXT> <CHANNEL_SEARCH_TEXT> => find downloaded video files for channel in VidHop videos metadata dir, with video titles (filenames) that match <TITLE_SEARCH_TEXT> and a channels whose name matches <CHANNEL_SEARCH_TEXT>"
   echo "    fvidc <SEARCH_TEXT> => find videos where title or description matches <SEARCH_TEXT> in all channels metadata"
-  echo "    fvidcv <CHANNEL_NAME> <SEARCH_TEXT> => find videos where title or description matches <SEARCH_TEXT> in channel with a name that matches <CHANNEL_NAME in a channels metadata"
-  echo "    fvidcv <CHANNEL_NAME> <SEARCH_TEXT> <PLATFORM> => find videos where title or description matches <SEARCH_TEXT> in channel with a name that matches <CHANNEL_NAME in a channels metadata for <PLATFORM> e.g youtube"
+  echo "    fvidcv <CHANNEL_NAME> <SEARCH_TEXT> [<PLATFORM>] => find videos where title or description matches <SEARCH_TEXT> in channel with a name that matches <CHANNEL_NAME in a channels metadata for <PLATFORM> e.g youtube.com"
+  echo "    fvidcv <CHANNEL_JSON_ABS_PATH> <SEARCH_TEXT> =>  find videos where title or description matches <SEARCH_TEXT> in channel with provided metadata JSON file"
   echo "    fvidusermeta <SEARCH_TEXT>  => find videos where user added metadata contains <SEARCH_TEXT>, execute 'metadata_help' for more information."
   echo "    chani <CHANNEL_NAME> => channel information, lists all videos of a channel with name matching <CHANNEL_NAME>"
   echo "    chani <CHANNEL_NAME> <PLATFORM> => channel information, lists all videos of a channel with name matching <CHANNEL_NAME> with platform matching <PLATFORM>"
@@ -141,7 +142,21 @@ function say() {
   echo -e "${NC}$1"
 }
 
-function find_one_meta() {
+function find_one_file() {
+  [ -z "$1" ] || [ -z "$2" ] && echo "usage: find_one <TYPE_FILE_OR_DIR> <PARTIAL_NAME> [<DIRECTORY>]" && return
+  if [ -n "$3" ];then search_dir="$3"; else search_dir="$wt_projects_dir"; fi
+  search_text="$2"
+  type="$1"
+
+  result=$(find "$search_dir" -type "$type" -iwholename "*$search_text*")
+  unset search_text
+
+  [ "$(wc -w <<<"$result")" -eq 0 ] && echo -e "found no match for '$search_text', abort" && return 1
+  [ "$(wc -l <<<"$result")" -gt 1 ] && echo -e "found multiple possibilities for '$search_text', abort\n$result" && return 2
+  [ "$(wc -l <<<"$result")" -eq 1 ] && echo -e "$result"
+}
+
+function find_one_vmeta() {
   search_text="$1"
   platform="$2"
 
@@ -150,7 +165,7 @@ function find_one_meta() {
     meta_file="$search_text"
   else
     # $meta_file search.
-    results=$(find "$meta_dir" -type f -iwholename "*$platform*$search_text*metadata.json")
+    results=$(find "$vids_meta_dir" -type f -iwholename "*$platform*$search_text*metadata.json")
     [ -z "$results" ] && return 1
     count="$(wc -l <<<"$results")"
     [ "$count" -eq 1 ] && meta_file="$results" || return 2
@@ -158,6 +173,15 @@ function find_one_meta() {
 
   [ -f "$meta_file" ] && title=$(basename "$meta_file" .json)
   [ -n "$meta_file" ] && echo "$meta_file"
+}
+
+function find-one-cmeta() {
+  [ -z "$1" ] && echo "usage: find_one_cmeta <CHANNEL_SEARCH_TEXT> [<PLATFORM>]" && return
+  channel_search_text="$1"
+  platform="$2"
+  result=$(find_one_file f "$channel_search_text**$platform*metadata.json" "$channels_meta_dir")
+  [ ! $? = 0 ] && return
+  echo "$result"
 }
 
 function fvidv() {
@@ -221,20 +245,25 @@ function fvid() {
 }
 
 function fvidcv() {
-  if [ -n "$1" ]; then name="$1"; else echo "usage: fvidcv <CHANNEL_NAME> <SEARCH_TEXT> [<PLATFORM>]" && return 0; fi
-  if [ -n "$2" ]; then text=$(echo "$2" | tr '[:upper:]' '[:lower:]'); else echo "usage: fvidcv <CHANNEL_NAME> <SEARCH_TEXT> [<PLATFORM>]" && return 0; fi
+  usage="usage: fvidcv <CHANNEL_SEARCH_TEXT> <SEARCH_TEXT> [<PLATFORM>]\n       fvidcv <CHANNEL_JSON_ABS_PATH> <SEARCH_TEXT>"
+  if [ -n "$1" ]; then channel_search_name="$1"; else echo "$usage" && return 0; fi
+  if [ -n "$2" ]; then text=$(echo "$2" | tr '[:upper:]' '[:lower:]'); else echo "$usage" && return 0; fi
   platform="$3"
 
-  json_files=$(json_files_for_channel_name "$name" "$platform")
-  [ -z "$json_files" ] && echo no match found && return 0
-  [[ "$json_files" == *$'\n'* ]] && msg_multiple_channels_found "fvidc" && return 0
-  json_file="$json_files" && unset json_files # only one entry in json_files
+  if [ -f "$channel_search_name" ]; then
+    json_file="$channel_search_name"
+  else
+    json_files=$(json_files_for_channel_name "$channel_search_name" "$platform")
+    [ -z "$json_files" ] && echo no match found && return 0
+    [[ "$json_files" == *$'\n'* ]] && msg_multiple_channels_found "fvidc" && return 0
+    json_file="$json_files" && unset json_files # only one entry in json_files
+  fi
 
   results_json=$(
-    jq --arg text "$text" '.entries[] |
+    jq --arg search_text "$search_text" '.entries[] |
               select(
-                  ( if .title != null then select(.title | ascii_downcase | contains($text)) else empty end ) or
-                  ( if .description != null then select(.description | ascii_downcase | contains($text)) else empty end )
+                  ( if .title != null then select(.title | ascii_downcase | contains($search_text)) else empty end ) or
+                  ( if .description != null then select(.description | ascii_downcase | contains($search_text)) else empty end )
               )' "$json_file"
   )
   echo "search done"
@@ -246,7 +275,10 @@ function fvidcv() {
 
 function fvidfc() {
   [ -z "$1" ] || [ -z "$2" ] &&
-    echo "  usage: fvidfc <TITLE_SEARCH_TEXT> <CHANNEL_SEARCH_TEXT>" && return
+    echo "  usage: fvidfc <TITLE_SEARCH_TEXT> <CHANNEL_SEARCH_TEXT>" &&
+    echo "   info: find downloaded video files for channel in VidHop videos metadata dir," &&
+    echo "         with video titles (filenames) that match <TITLE_SEARCH_TEXT>" &&
+    echo "         and a channels whose name matches <CHANNEL_SEARCH_TEXT>" && return
   title_search_text="$(echo "$1" | tr '[:upper:]' '[:lower:]')"
   channel_search_text="$(echo "$2" | tr '[:upper:]' '[:lower:]')"
 
@@ -471,14 +503,15 @@ function print_channel_data() {
 
 # Show all videos of a channel, one line per video.
 function chani() { # channel info
-  init_vars "$@" || return
-  [ -z "$text" ] && echo navigated to channels metadata directory so you can tab autocomplete && return 0
+  [ -z "$1" ] &&
+    echo "usage: chani <CHANNEL_SEARCH_TEXT>" &&
+    echo "       chani <ABS_FILE_PATH> [<PLATFORM>]" && return
 
   if [ -f "$1" ]; then
     json_file="$1"
     json=$(jq '.' "$1")
   else
-    json_files=$(json_files_for_channel_name "$text" "$platform")
+    json_files=$(json_files_for_channel_name "$1" "$2")
     [ -z "$json_files" ] && echo no match found && return 0
     [[ "$json_files" == *$'\n'* ]] && msg_multiple_channels_found "chani" && return 0
     json_file="$json_files" && unset json_files # only one entry in json_files
