Updates.
Signed-off-by: wtechgo <wtechgo@proton.me>

diff --git a/bin/fvid b/bin/fvid
--- a/bin/fvid
+++ b/bin/fvid
@@ -119,12 +119,33 @@ function say() {
   [ "$quiet" = "true" ] && return
   if [ "$1" = "--overwrite" ] || [ "$1" = "-o" ]; then
     clearLastLine
-    file="$(echo "$2" | tr -d "'" | sed "s/.json//g")"  # remove quotes and '.json' from filename
+    file="$(echo "$2" | tr -d "'" | sed "s/.json//g")" # remove quotes and '.json' from filename
     # 1. remove VidHop root from path; 2. trim down to 'screensize - ".json" (5 chars)'; 3. append '.json'
     echo "$(echo -n "${file#$subtract}" | cut -c -"$(("$workstation_screen_char_count" - 5))").json"
     return
   fi
   echo -e "$1"
+}
+
+function find_one_meta() {
+  search_text="$1"
+  platform="$2"
+
+  # $meta_file determination.
+  if [ -f "$search_text" ]; then
+    meta_file="$search_text"
+  else
+    # $meta_file search.
+    results=$(find "$vids_meta_dir" -type f -iwholename "*$platform*$search_text*.json")
+    [ -z "$results" ] && return 1
+    count="$(wc -l <<<"$results")"
+    [ "$count" -eq 1 ] && meta_file="$results" || return 2
+  fi
+
+  [ -f "$meta_file" ] && title=$(basename "$meta_file" .json)
+  #  media_file="$(find "$vidhop_dir" -type f -iname "$title")"
+
+  [ -n "$meta_file" ] && echo "$meta_file"
 }
 
 function fvidv() {
@@ -205,15 +226,71 @@ function fvidcv() {
 # Output all video files whose name match your query.
 function fvidf() { # find video files (on disk)
   text="$1"
+  unset result && found_something="false"
 
-  echo "\n>>> recursive search results for DLV single videos:"
-  find "$vids_dir" -type f -iname "*$text*.mp4" | sed "s/^/'/;s/$/'/" | sort # sed adds quotes for filenames with spaces
+  result=$(find "$vids_dir" -type f -iname "*$text*.mp4" | sed "s/^/'/;s/$/'/" | sort) # sed adds quotes for filenames with spaces
+  [ "$(wc --words <<<"$result")" -gt 0 ] &&
+    echo -e "> Single video downloads in VidHop directory search result:" && echo -e "$result" &&
+    unset result && found_something="true"
 
-  echo "\n>>> recursive search results for DLV channels:"
-  find "$channels_dir" -type f -iname "*$text*.mp4" | sed "s/^/'/;s/$/'/" | sort
+  result=$(find "$channels_dir" -type f -iname "*$text*.mp4" | sed "s/^/'/;s/$/'/" | sort)
+  [ "$(wc --words <<<"$result")" -gt 0 ] &&
+    echo -e "> Channel downloads in VidHop directory search result:" && echo -e "$result" &&
+    unset result && found_something="true"
 
-  echo "\n>>> recursive search results in default videos directory in \$HOME:"
-  find "$HOME/Videos" -type f -not -path "$vidhop_dir" -iname "*$text*.mp4" | sed "s/^/'/;s/$/'/" | sort
+  result=$(find "$HOME/Videos" -type f -not -path "$vidhop_dir" -iname "*$text*.mp4" | sed "s/^/'/;s/$/'/" | sort)
+  [ "$(wc --words <<<"$result")" -gt 0 ] &&
+    echo -e "> Videos in user home directory result:" && echo -e "$result" &&
+    unset result && found_something="true"
+
+  [ "$found_something" = "false" ] && echo "found nothing"
+}
+
+function format_usermeta() {
+  jq '.entries | unique_by(.webpage_url) | sort_by(.upload_date) | .[]
+          | "> " +
+            (if .uploader == null then .channel else .uploader end) +
+            ": " + .title +
+            " | " + .webpage_url +
+            " | " + .upload_date +
+            (if .vh_speakers != null then " | speakers: " + .vh_speakers else null end) +
+            (if .vh_summary != null then " | summary: " + .vh_summary else null end) +
+            (if .vh_description != null then " | description: " + .vh_description else null end) +
+            (if .vh_topics != null then " | topics: " + .vh_topics else null end) +
+            (if .vh_categories != null then " | categories: " + .vh_categories else null end)' <<<"$json" | tr -d '"'
+}
+
+function print_usermeta() {
+  echo -e "${GREEN}$(format_usermeta)"
+}
+
+function fvidusermeta() {
+  init_vars "$@" || return
+  case $? in # exit code of init_vars
+  1) echo "failed to initiate vars (function init_vars)" ;;
+  2) return 0 ;; # fvid --help was called and shown, exit program.
+  esac
+
+  say "Searching in vidhop videos metadata at $vids_meta_dir..."
+  say "Searching in single videos metadata...\n"
+  while read -r vidjson; do
+    subtract="$vids_meta_dir/" && say -o "$vidjson"
+    json+=$(
+      jq --arg text "$text" '
+            select(
+              ( if .vh_speakers != null then select(.vh_speakers | ascii_downcase | contains($text)) else null end ) or
+              ( if .vh_summary != null then select(.vh_summary | ascii_downcase | contains($text)) else null end ) or
+              ( if .vh_description != null then select(.vh_description | ascii_downcase | contains($text)) else null end ) or
+              ( if .vh_topics != null then select(.vh_topics | ascii_downcase | contains($text)) else null end ) or
+              ( if .vh_categories != null then select(.vh_categories | ascii_downcase | contains($text)) else null end )
+            )' "$vidjson"
+    )
+  done < <(find "$vids_meta_dir" -type f -iname "*.json") && clearLastLine
+  echo "search done"
+
+  json=$(jq -s '{ entries: . }' <<<"$json")
+  [ "$(jq '.entries | length' <<<"$json")" -eq 0 ] && echo "found nothing" && return
+  print_usermeta
 }
 
 function fvid() {
@@ -278,16 +355,14 @@ function json_files_for_channel_name() {
 }
 
 function print_channel_data() {
-  url_msg="url     : $(channel_url_from_file "$json_file")"
-  line=""
-  for ((i = 1; i < $(echo "$url_msg" | wc -c); i++)); do
-    line+="_"
-  done && echo -e "$line"
+  url_msg="    name: $(basename "$json_file" ".json")"
+  line=$(print_line_for_msg "$url_msg")
 
-  echo "name    : $(basename "$json_file" ".json")"
-  echo "url     : $(channel_url_from_file "$json_file")"
+  echo "    name: $(basename "$json_file" ".json")"
+  echo "$line"
+  echo "     url: $(channel_url_from_file "$json_file")"
   echo "platform: $(extract_platform_name "$json_file")"
-  echo "videos  : $(jq '.entries | length' <<<"$json")"
+  echo "  videos: $(jq '.entries | length' <<<"$json")"
 }
 
 # Show all videos of a channel, one line per video.
