Fix dlci bug for the scenario when there's no channel name in the metadata JSON.

diff --git a/bin/fvid b/bin/fvid
--- a/bin/fvid
+++ b/bin/fvid
@@ -49,9 +49,12 @@ function init_vars() {
 }
 
 function format_oneliner() {
-  jq '.entries | unique_by(.webpage_url) | sort_by(.upload_date) | .[]
+  channel_name_fallback="$(url_to_channel_name "$(jq .webpage_url <<<"$json" | tr -d '"')")"
+  jq --arg 'channel_name_fallback' "$channel_name_fallback" '.entries | unique_by(.webpage_url) | sort_by(.upload_date) | .[]
           | "> " +
-            (if .uploader == null then .channel else .uploader end) + ": " +
+            (if .uploader != null then .uploader else
+              (if .channel != null then .channel else $channel_name_fallback end)
+            end) + ": " +
             .title + " | " +
             .webpage_url + " | " +
             .upload_date' <<<"$json" | tr -d '"'
@@ -143,8 +146,6 @@ function find_one_meta() {
   fi
 
   [ -f "$meta_file" ] && title=$(basename "$meta_file" .json)
-  #  media_file="$(find "$vidhop_dir" -type f -iname "$title")"
-
   [ -n "$meta_file" ] && echo "$meta_file"
 }
 
@@ -293,6 +294,35 @@ function fvidusermeta() {
   print_usermeta
 }
 
+function fvidusermeta() {
+  init_vars "$@" || return
+  case $? in # exit code of init_vars
+  1) echo "failed to initiate vars (function init_vars)" ;;
+  2) return 0 ;; # fvid --help was called and shown, exit program.
+  esac
+
+  say "Searching in vidhop videos metadata at $vids_meta_dir..."
+  say "Searching in single videos metadata...\n"
+  while read -r vidjson; do
+    subtract="$vids_meta_dir/" && say -o "$vidjson"
+    json+=$(
+      jq --arg text "$text" '
+            select(
+                ( if .vh_summary != null then select(.vh_summary | ascii_downcase | contains($text)) else empty end ) or
+                ( if .vh_description != null then select(.vh_description | ascii_downcase | contains($text)) else empty end ) or
+                ( if .vh_speakers != null then select(.vh_speakers | ascii_downcase | contains($text)) else empty end ) or
+                ( if .vh_topics != null then select(.vh_topics | ascii_downcase | contains($text)) else empty end ) or
+                ( if .vh_categories != null then select(.vh_categories | ascii_downcase | contains($text)) else empty end )
+            )' "$vidjson"
+    )
+  done < <(find "$vids_meta_dir" -type f -iname "*.json") && clearLastLine
+  echo "search done"
+
+  json=$(jq -s '{ entries: . }' <<<"$json")
+  [ "$(jq '.entries | length' <<<"$json")" -eq 0 ] && echo "found nothing" && return
+  print_usermeta
+}
+
 function fvid() {
   init_vars "$@" || return
   case $? in # exit code of init_vars
@@ -355,13 +385,13 @@ function json_files_for_channel_name() {
 }
 
 function print_channel_data() {
-  url_msg="    name: $(basename "$json_file" ".json")"
+  url="$(channel_url_from_file "$json_file")"
+  url_msg="     url: $url"
   line=$(print_line_for_msg "$url_msg")
-
-  echo "    name: $(basename "$json_file" ".json")"
   echo "$line"
-  echo "     url: $(channel_url_from_file "$json_file")"
-  echo "platform: $(extract_platform_name "$json_file")"
+  echo "    name: $(basename "$json_file" ".json")"
+  echo "     url: $url"
+  echo "platform: $(extract_platform_name "$url")"
   echo "  videos: $(jq '.entries | length' <<<"$json")"
 }
 
