Improve tor module.

diff --git a/bin/tor b/bin/tor
--- a/bin/tor
+++ b/bin/tor
@@ -57,17 +57,21 @@ tor-electron() {
 
 # Tor browser
 
-tor_data_dir="$HOME/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Tor"
-
 run-checks-torbrowser() {
   ! [ -d "$tor_data_dir" ] &&
-    echo "directory containing to torrc-defaults does not exist at '$tor_data_dir', abort" && return
+    echo "directory containing to torrc-defaults does not exist at '$tor_data_dir', abort" && return 1
 
   ! [ -f "$tor_data_dir/torrc-defaults.original" ] &&
     /bin/cp "$tor_data_dir/torrc-defaults" "$tor_data_dir/torrc-defaults.original"
 
   ! [ -f "$tor_data_dir/torrc-defaults.bak" ] &&
     /bin/cp "$tor_data_dir/torrc-defaults" "$tor_data_dir/torrc-defaults.bak"
+
+  if ! [ -f "$tor_data_dir/torrc.original" ] && [ -f "$tor_data_dir/torrc" ];then
+    /bin/cp "$tor_data_dir/torrc" "$tor_data_dir/torrc.original"
+  fi
+
+  return 0
 }
 
 torbrowser-country-search() {
@@ -91,10 +95,12 @@ torbrowser-country() {
 
   country_code="$1"
   ! grep -iq "$country_code" <<<"$tor_country_codes" &&
-    echo "country code '$country_code' is not  a valid Tor country code, abort" && return
+    echo "country code '$country_code' is not a valid Tor country code, abort" && return
 
   torbrowser-set-torrc-for-country "$country_code"
-  torbrowser-launcher
+
+  [ "$torbrowser_app" = "torbrowser-launcher" ] && "$torbrowser_app" && return
+  "$torbrowser_app" --detach
 }
 
 torbrowser-usa() {
@@ -111,11 +117,13 @@ torbrowser-czech() {
 
 torbrowser-default() {
   run-checks-torbrowser
+  [ $? = 1 ] && return
   /bin/cp "$tor_data_dir/torrc-defaults.bak" "$tor_data_dir/torrc-defaults"
 }
 
 torbrowser-reset() {
   run-checks-torbrowser
+  [ $? = 1 ] && return
   /bin/cp "$tor_data_dir/torrc-defaults.original" "$tor_data_dir/torrc-defaults"
 }
 
@@ -131,6 +139,22 @@ torbrowser-set-torrc-for-country() {
     echo "country code '$country_code' is not  a valid Tor country code, abort" && return 1
 
   run-checks-torbrowser
+  [ $? = 1 ] && return
+
+  cat <<EOF >"$tor_data_dir/torrc"
+# This file was generated by Tor; if you edit it, comments will not be preserved
+# The old torrc file was renamed to torrc.orig.1, and Tor will ignore it
+
+ClientOnionAuthDir /home/freetalk/.local/share/torbrowser/Browser/TorBrowser/Data/Tor/onion-auth
+DataDirectory /home/freetalk/.local/share/torbrowser/Browser/TorBrowser/Data/Tor
+GeoIPFile /home/freetalk/.local/share/torbrowser/Browser/TorBrowser/Data/Tor/geoip
+GeoIPv6File /home/freetalk/.local/share/torbrowser/Browser/TorBrowser/Data/Tor/geoip6
+
+ExitNodes {$country_code} StrictNodes 1
+EOF
+
+
+## Torbrowser-launcher with torrc-defaults
 
   cat <<EOF >"$tor_data_dir/torrc-defaults"
 # torrc-defaults for Tor Browser
@@ -155,7 +179,6 @@ ClientTransportPlugin webtunnel exec ./TorBrowser/Tor/PluggableTransports/webtun
 ClientTransportPlugin conjure exec ./TorBrowser/Tor/PluggableTransports/conjure-client -registerURL https://registration.refraction.network/api
 
 ExitNodes {$country_code} StrictNodes 1
-
 EOF
 }
 
